// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/building": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/building";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/common/building.tsx": {
    id: "routes/common/building";
    page: "/building";
  };
};